export const LoginAction = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
  SHOWLOADING: 'SHOWLOADING',
  LOGIN_FULLNAME: 'LOGIN_FULLNAME',
  LOGED_USER_INFO: 'LOGED_USER_INFO',
  FETCH_USERINFO: 'FETCH_USERINFO',
  FETCH_USERINFO_ERROR: 'FETCH_USERINFO_ERROR',
  USER_TOKEN: 'USER_TOKEN',
  REMOVE_USER_TOKEN: 'REMOVE_USER_TOKEN',
  SET_EXPIRY_DATE_INFO: 'SET_EXPIRY_DATE_INFO',
}