export const PaymentAction = {
  PAYMENT: 'PAYMENT',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_ERROR: 'PAYMENT_ERROR',
  PAYMENT_VERIFY: 'PAYMENT_VERIFY',
  PAYMENT_VERIFY_SUCCESS: 'PAYMENT_VERIFY_SUCCESS',
  PAYMENT_VERIFY_ERROR: 'PAYMENT_VERIFY_ERROR',
  TRANSACTION: 'TRANSACTION',
  TRANSACTION_SUCCESS: 'TRANSACTION_SUCCESS',
  TRANSACTION_ERROR: 'TRANSACTION_ERROR'
}